insert into AdProductList values('Air Elite')
insert into AdProductList values('Air')
insert into AdProductList values('Luxe Scooter')
insert into AdProductList values('Other')
insert into AdProductList values('Perfect Sleep Chair')
insert into AdProductList values('So Lite Glide')
insert into AdProductList values('So Lite Scooter')
insert into AdProductList values('So Lite Wheelchair')
insert into AdProductList values('Toilet Lift')
insert into AdProductList values('UpBed')
insert into AdProductList values('UpWalker')
insert into AdProductList values('Zinger')
insert into AdProductList values('Zoomer')