insert into AdVersionDetails(AdVersionID, Product)Values('146538', 'Perfect Sleep Chair')
insert into AdVersionDetails(AdVersionID, Product)Values('146641', 'Perfect Sleep Chair')
insert into AdVersionDetails(AdVersionID, Product)Values('146642', 'Perfect Sleep Chair')
insert into AdVersionDetails(AdVersionID, Product)Values('185044', 'Zoomer')
insert into AdVersionDetails(AdVersionID, Product)Values('185055', 'Zoomer')
insert into AdVersionDetails(AdVersionID, Product)Values('185057', 'Zoomer')
insert into AdVersionDetails(AdVersionID, Product)Values('185251', 'Zinger')
insert into AdVersionDetails(AdVersionID, Product)Values('185253', 'Zinger')
insert into AdVersionDetails(AdVersionID, Product)Values('185404', 'Upbed')
insert into AdVersionDetails(AdVersionID, Product)Values('185675', 'So Lite Scooter')
insert into AdVersionDetails(AdVersionID, Product)Values('185684', 'So Lite Scooter')
insert into AdVersionDetails(AdVersionID, Product)Values('185685', 'So Lite Scooter')
insert into AdVersionDetails(AdVersionID, Product)Values('186001', 'Luxe Scooter')
insert into AdVersionDetails(AdVersionID, Product)Values('187001', 'Air Elite')
insert into AdVersionDetails(AdVersionID, Product)Values('187002', 'Air Elite')
insert into AdVersionDetails(AdVersionID, Product)Values('187003', 'Air Elite')
insert into AdVersionDetails(AdVersionID, Product)Values('187007', 'Perfect Sleep Chair')
insert into AdVersionDetails(AdVersionID, Product)Values('187008', 'Perfect Sleep Chair')
insert into AdVersionDetails(AdVersionID, Product)Values('187009', 'Zoomer')
insert into AdVersionDetails(AdVersionID, Product)Values('187010', 'Air Elite')
insert into AdVersionDetails(AdVersionID, Product)Values('187011', 'Perfect Sleep Chair')
insert into AdVersionDetails(AdVersionID, Product)Values('187012', 'Zoomer')
insert into AdVersionDetails(AdVersionID, Product)Values('187013', 'So Lite Scooter')
insert into AdVersionDetails(AdVersionID, Product)Values('46641', 'Perfect Sleep Chair')
insert into AdVersionDetails(AdVersionID, Product)Values('46642', 'Perfect Sleep Chair')
insert into AdVersionDetails(AdVersionID, Product)Values('85044', 'Zoomer')
insert into AdVersionDetails(AdVersionID, Product)Values('85057', 'Zoomer')
insert into AdVersionDetails(AdVersionID, Product)Values('85253', 'Zinger')
insert into AdVersionDetails(AdVersionID, Product)Values('85254', 'Zinger')
insert into AdVersionDetails(AdVersionID, Product)Values('85255', 'Zinger')
insert into AdVersionDetails(AdVersionID, Product)Values('85404', 'Upbed')
insert into AdVersionDetails(AdVersionID, Product)Values('85675', 'So Lite Scooter')
insert into AdVersionDetails(AdVersionID, Product)Values('85684', 'So Lite Scooter')
insert into AdVersionDetails(AdVersionID, Product)Values('86001', 'Luxe Scooter')
insert into AdVersionDetails(AdVersionID, Product)Values('87002', 'Air Elite')
insert into AdVersionDetails(AdVersionID, Product)Values('87003', 'Air Elite')
insert into AdVersionDetails(AdVersionID, Product)Values('87011', 'Perfect Sleep Chair')
insert into AdVersionDetails(AdVersionID, Product)Values('87012', 'Zoomer')
insert into AdVersionDetails(AdVersionID, Product)Values('87015', 'Perfect Sleep Chair')
insert into AdVersionDetails(AdVersionID, Product)Values('ADVNEW', 'Other')
insert into AdVersionDetails(AdVersionID, Product)Values('PSCSP24', 'Perfect Sleep Chair')
insert into AdVersionDetails(AdVersionID, Product)Values('PSCW23', 'Perfect Sleep Chair')