--select distinct offerNumber, product,
--concat('insert into OfferDetails(AdVersionID, Product) values(''', offerNumber, ''', ''', product, ''')')
--FROM dbo.ADVERTISING INNER JOIN DW_PUB on ADVERTISING.pubCode = DW_PUB.pubCode
--where 
--((adCode >= '120000' and adCode < '130000' and len(adCode) > 4)
--or 
--(adCode >= '603000' and adCode < '613000' and len(adCode) > 4))



insert into OfferDetails(AdVersionID, Product) values('146538', 'Perfect Sleep Chair')
insert into OfferDetails(AdVersionID, Product) values('146641', 'Perfect Sleep Chair')
insert into OfferDetails(AdVersionID, Product) values('146642', 'Perfect Sleep Chair')
insert into OfferDetails(AdVersionID, Product) values('185044', 'Zoomer')
insert into OfferDetails(AdVersionID, Product) values('185055', 'Zoomer')
insert into OfferDetails(AdVersionID, Product) values('185057', 'Zoomer')
insert into OfferDetails(AdVersionID, Product) values('185251', 'Zinger')
insert into OfferDetails(AdVersionID, Product) values('185253', 'Zinger')
insert into OfferDetails(AdVersionID, Product) values('185404', 'Upbed')
insert into OfferDetails(AdVersionID, Product) values('185675', 'So Lite Scooter')
insert into OfferDetails(AdVersionID, Product) values('185684', 'So Lite Scooter')
insert into OfferDetails(AdVersionID, Product) values('185685', 'So Lite Scooter')
insert into OfferDetails(AdVersionID, Product) values('186001', 'Luxe Scooter')
insert into OfferDetails(AdVersionID, Product) values('187001', 'Air Elite')
insert into OfferDetails(AdVersionID, Product) values('187002', 'Air Elite')
insert into OfferDetails(AdVersionID, Product) values('187003', 'Air Elite')
insert into OfferDetails(AdVersionID, Product) values('187007', 'Perfect Sleep Chair')
insert into OfferDetails(AdVersionID, Product) values('187008', 'Perfect Sleep Chair')
insert into OfferDetails(AdVersionID, Product) values('187009', 'Zoomer')
insert into OfferDetails(AdVersionID, Product) values('187010', 'Air Elite')
insert into OfferDetails(AdVersionID, Product) values('187011', 'Perfect Sleep Chair')
insert into OfferDetails(AdVersionID, Product) values('187012', 'Zoomer')
insert into OfferDetails(AdVersionID, Product) values('187013', 'So Lite Scooter')
insert into OfferDetails(AdVersionID, Product) values('46641', 'Perfect Sleep Chair')
insert into OfferDetails(AdVersionID, Product) values('46642', 'Perfect Sleep Chair')
insert into OfferDetails(AdVersionID, Product) values('85044', 'Zoomer')
insert into OfferDetails(AdVersionID, Product) values('85057', 'Zoomer')
insert into OfferDetails(AdVersionID, Product) values('85253', 'Zinger')
insert into OfferDetails(AdVersionID, Product) values('85254', 'Zinger')
insert into OfferDetails(AdVersionID, Product) values('85255', 'Zinger')
insert into OfferDetails(AdVersionID, Product) values('85404', 'Upbed')
insert into OfferDetails(AdVersionID, Product) values('85675', 'So Lite Scooter')
insert into OfferDetails(AdVersionID, Product) values('85684', 'So Lite Scooter')
insert into OfferDetails(AdVersionID, Product) values('86001', 'Luxe Scooter')
insert into OfferDetails(AdVersionID, Product) values('87001', 'Air Elite')
insert into OfferDetails(AdVersionID, Product) values('87002', 'Air Elite')
insert into OfferDetails(AdVersionID, Product) values('87003', 'Air Elite')
insert into OfferDetails(AdVersionID, Product) values('87011', 'Perfect Sleep Chair')
insert into OfferDetails(AdVersionID, Product) values('87012', 'Zoomer')
insert into OfferDetails(AdVersionID, Product) values('87015', 'Perfect Sleep Chair')
insert into OfferDetails(AdVersionID, Product) values('ADVNEW', 'Other')
insert into OfferDetails(AdVersionID, Product) values('PSCW23', 'Perfect Sleep Chair')