--select distinct a.pubCode, p.description, category,
--concat('insert into SourceDetails(AdVersionID, PrimaryName, Category) values(''', a.pubCode, ''', ''', description, ''', ''', category,''')')
--FROM dbo.ADVERTISING a inner join 
--		SOURCES s on a.adCode = s.REFSOURCE inner join
--		DW_PUB p on a.pubCode = p.pubCode
--where 
--((adCode >= '120000' and adCode < '130000' and len(adCode) > 4)
--or 
--(adCode >= '603000' and adCode < '613000' and len(adCode) > 4))
--order by a.pubCo

insert into SourceDetails(AdVersionID, PrimaryName, Category) values('40', 'INDEPENDENT BUSINESS', 'BI')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('45', 'MOTHER JONES', 'BI')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('419', 'ELKS MAGAZINE', 'BI')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('422', 'TV GUIDE', 'OW')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('540', 'WOMANS WORLD', 'OW')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1162', 'TEXAS CO-OP POWER', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1325', 'NATIONAL EXAMINER', 'OW')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1343', 'NATIONAL ENQUIRER', 'OW')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1417', 'AMERICAN HISTORY', 'BI')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1424', 'VIETNAM', 'BI')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1425', 'WILD WEST', 'BI')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1485', 'SOAP OPERA DIGEST', 'OW')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1551', 'VFW MAGAZINE', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1570', 'FAMILY TREE', 'BI')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1576', 'ARCHAEOLOGY MAGAZINE', 'BI')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1621', 'GOOD OLD DAYS', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1635', 'AAA-VIA', 'BI')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1639', 'BIBLICAL ARCHAEOLOGY REVIEW', 'BI')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1671', 'WWII HISTORY', 'BI')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1710', 'SATURDAY EVENING POST, THE', 'BI')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1723', 'AMERICAN LEGION MAGAZINE, THE', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1745', 'ARTISTS MAGAZINE, THE', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1751', 'MOOSE MAGAZINE', 'QU')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1777', 'AARP-MODERN MATURITY-70+', 'BI')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1790', 'NARFE', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1823', 'ALABAMA LIVING', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1833', 'CAROLINA COUNTRY', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1836', 'GLOBE/NATIONAL EXAMINER/SUN', 'XX')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1918', 'READERS DIGEST LARGE PRINT', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1926', 'COOPERATIVE LIVING', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1928', 'KENTUCKY LIVING', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1931', 'LOUISIANA COUNTRY', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1933', 'OKLAHOMA LIVING', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1934', 'RURAL MISSOURI', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1935', 'TODAY IN MISSISSIPPI', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1936', 'WISCONSIN ENERGY CO-OP NEWS', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1939', 'NEWSMAX MAGAZINE', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1963', 'COLORADO COUNTRY LIFE', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1978', 'PENN LINES', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1996', 'ILLINOIS COUNTRY LIVING', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('1998', 'NORTH DAKOTA LIVING', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('2000', 'WREN, THE', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('2034', 'NEW MEXICO ENCHANTMENT', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('2036', 'RURALITE', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('2102', 'AARP BULLETIN', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('2201', 'FRA TODAY', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('2204', 'GLOBE GROUP', 'OW')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('2301', 'QUILTMAKER', 'BI')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('2599', 'MISSISSIPPI FARM COUNTRY', 'BI')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('2618', 'TODAYS SENIOR MAGAZINE', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('2628', 'BIRDS & BLOOMS', 'BI')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('2726', 'GEORGIA NEIGHBORS', 'QU')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('2753', 'TENNESSEE MAGAZINE', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('2824', 'TV WEEKLY', 'OW')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('2865', 'GLOBE / NATIONAL EXAMINER (WAS', 'NW')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('2888', 'ARKANSAS LIVING', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('2889', 'FLORIDA CURRENTS', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('2899', 'SOUTH CAROLINA LIVING', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('2930', 'AAA-SOUTHERN TRAVELER', 'BI')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('2940', 'ANTIQUE POWER', 'BI')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('3155', 'CLOSER', 'OW')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('3171', 'NEA RETIRED (WAS THIS ACTIVE L', 'BI')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('3225', 'LIGUORIAN MAGAZINE', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('3248', 'HEMMINGS CLASSIC CAR', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('3282', 'OLD CARS WEEKLY', 'XX')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('3368', 'OHIO COOPERATIVE LIVING (WAS C', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('3419', 'NUMISMATIC NEWS', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('3432', 'INDIANA CONNECTION (WAS INDIAN', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('3468', 'Tennessee Home and Farm', 'QU')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('3474', 'North Carolina Field & Family', 'QU')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('3477', 'Nebraska Magazine', 'MO')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('3479', 'Florida Farm and Family', 'BI')
insert into SourceDetails(AdVersionID, PrimaryName, Category) values('10149', 'INCREMENTAL INSERTS', 'MO')